export const SUMMARY_DATA_AVAILABLE = "SUMMARY_DATA_AVAILABLE"
export const SUMMARY_DATA_NOT_AVAILABLE = "SUMMARY_DATA_NOT_AVAILABLE"
export const CRYPTOCURRENCIES_DATA_AVAILABLE = "CRYPTOCURRENCIES_DATA_AVAILABLE"
export const CRYPTOCURRENCIES_DATA_NOT_AVAILABLE = "CRYPTOCURRENCIES_DATA_NOT_AVAILABLE"